spring:
  application:
    name: eureka-server

  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: 10322
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
